config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :dakokus

app/models/dakoku_datetime.rb
# -*- coding: utf-8 -*-
class DakokuDatetime < ActiveRecord::Base
  unloadable

  belongs_to :user

  module UserExtention
    def self.included(base)
      base.class_eval do
        has_many :dakoku_datetimes
      end
    end
  end

  def to_param  # overridden
    dakoku_at
  end

  NORMAL_WORK = 1 # 通常出勤
  HOLIDAY_WORK = 2 # 休日出勤
  HOLIDAY = 3 # 休日（休んだらコメントに何か書く）

  def normal_work?
    status == NORMAL_WORK
  end

  def holiday_work?
    status == HOLIDAY_WORK
  end

  def holiday?
    status == HOLIDAY
  end

  def status_text
    case status
    when NORMAL_WORK
      "通常出勤"
    when HOLIDAY_WORK
      "休日出勤"
    when HOLIDAY
      "休日"
    end
  end
end

app/controllers/dakokus_controller.rb
# -*- coding: utf-8 -*-
class DakokusController < ApplicationController
  unloadable

  before_filter :find_dakoku
  # 打刻変更ページ
  def edit
  end

  def update
    if @dakoku.update_attributes(params[:dakoku_datetime])
      redirect_to my_page_path, :notice => "打刻修正を行いました。"
    else
      render :edit
    end
  end

  private

  def find_dakoku
    @dakoku = find_current_user.dakoku_datetimes.where(:dakoku_at => params[:id]).first_or_initialize
  end
end

app/helpers/dakokus_helper.rb
module DakokusHelper
end

app/views/dakokus/edit.html.erb
<h2>打刻編集</h2>

<%= form_for @dakoku, :url => dakoku_path(@dakoku), :method => :put do |f| %>
  <div class="splitcontentleft">
    <fieldset class="box tabular">
      <legend>打刻</legend>
      <p><label for="start_at">出社</label><%= f.datetime_select :start_at, :default => { :hour => 9, :minute => 00 } %></p>
      <p><label for="start_at">退社</label><%= f.datetime_select :end_at, :default => { :hour => 21, :minute => 00 } %></p>
      <p><label>タイプ</label><%= f.select :status, [["通常出勤", DakokuDatetime::NORMAL_WORK],["休日出勤", DakokuDatetime::HOLIDAY_WORK],["休日", DakokuDatetime::HOLIDAY]] , :html=>{ :selected => DakokuDatetime::NORMAL_WORK } %></p>
      <p><label for="commet">コメント</label><%= f.text_area :comment, :size => "50x10" %></p>
    </fieldset>
    <%= f.submit "編集" %>
<% end %>

app/views/my/blocks/_dakoku.html.erb
<h3><%= t('dakoku') %></h3>
<p style="float:right;">
<%= link_to_previous_month(@year, @month) %> | <%= link_to_next_month(@year, @month) %>
</p>
<% dakokus = @user.dakoku_datetimes.where('dakoku_at >= :startdt AND dakoku_at <= :enddt', startdt: @calendar.startdt, enddt: @calendar.enddt).all %>
<table class="cal">
  <thead>
    <tr><th scope="col" title="<%= l(:label_week) %>" class="week-number"></th><% 7.times do |i| %><th scope="col"><%= day_name( (@calendar.first_wday+i)%7 ) %></th><% end %></tr>
  </thead>
  <tbody>
    <tr>
      <% day = @calendar.startdt
      while day <= @calendar.enddt %>
    <%= ("<td class='week-number' title='#{ l(:label_week) }'>#{(day+(11-day.cwday)%7).cweek}</td>".html_safe) if day.cwday == @calendar.first_wday %>
    <td class="<%= day.month==@calendar.month ? 'even' : 'odd' %><%= ' today' if Date.today == day %>">
      <p class="day-num"><%= day.day %></p>
      <% if dakoku = dakokus.find{|x| x.dakoku_at == day} %>
        <div class="tooltip">
          <% if dakoku.holiday? %>
            <strong>タイプ</strong>：<%= dakoku.status_text %><br />
            <strong>コメント</strong>：<%= truncate(dakoku.comment, :length => 30) %>
            <span class="tip">
              <strong>タイプ</strong>：<%= dakoku.status_text %><br />
              <strong>コメント</strong>：<%= truncate(dakoku.comment, :length => 30) %>
              <%= link_to "修正", edit_dakoku_path(dakoku) %>
            </span>
          <% else %>
            <strong>出社</strong>：<%= dakoku.start_at.strftime("%H:%M") %><br />
            <strong>退社</strong>：<%= dakoku.end_at.strftime("%H:%M") %><br />
            <strong>タイプ</strong>：<%= dakoku.status_text %><br />
            <strong>コメント</strong>：<%= truncate(dakoku.comment, :length => 30) %>
            <span class="tip">
              <strong>出社</strong>：<%= dakoku.start_at.strftime("%H:%M") %><br />
              <strong>退社</strong>：<%= dakoku.end_at.strftime("%H:%M") %><br />
              <strong>タイプ</strong>：<%= dakoku.status_text %><br />
              <strong>コメント</strong>：<%= dakoku.comment %><br />
              <%= link_to "修正", edit_dakoku_path(dakoku) %>
            </span>
          <% end %>
      </div>
      <% else %>
        <strong>未記録</strong><br />
        <br />
        <%= link_to "打刻", edit_dakoku_path(DakokuDatetime.new(:dakoku_at => day)) %>
      <% end %>
    </td>
    <%= '</tr><tr>'.html_safe if day.cwday==@calendar.last_wday and day!=@calendar.enddt %>
    <% day = day + 1
      end %>
  </tr>
</tbody>
</table>